# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               stackDB Blog
tagline:             the official
description:         'This is the official blog of <a href="https://stackdb.net" target="_blank">stackDB.net</a>. We will post news and other related content here to keep the main site clean.'
url:                 http://blog.stackdb.net
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              stackDB
  email:             contact@stackdb.net
# Custom vars
version:             1.0.0
